apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "grafana.server.fullname" . }}
type: Opaque
data:
  {{- if .Values.server.adminPassword }}
  grafana-admin-password: {{ .Values.server.adminPassword | b64enc | quote }}
  {{- else }}
  grafana-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  grafana-admin-user: {{ .Values.server.adminUser | b64enc | quote }}
  {{- if .Values.server.githubAuth.clientSecret }}
  grafana-github-client-secret: {{ .Values.server.githubAuth.clientSecret | b64enc | quote }}
  {{- end }}
